# Generated by Django 3.2.7 on 2021-10-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abirvab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoiReview',
            fields=[
                ('boiReviewId', models.IntegerField(primary_key=True, serialize=False)),
                ('boiReviewText', models.TextField()),
                ('boiReviewFile', models.FileField(upload_to='')),
                ('authorFirstName', models.CharField(max_length=15)),
                ('authorLastName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Chobi',
            fields=[
                ('chobiId', models.IntegerField(primary_key=True, serialize=False)),
                ('chobiField', models.ImageField(upload_to='images')),
                ('chobiText', models.TextField()),
                ('authorFirstName', models.CharField(max_length=15)),
                ('authorLastName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaReview',
            fields=[
                ('cinemaReviewId', models.IntegerField(primary_key=True, serialize=False)),
                ('cinemaReviewText', models.TextField()),
                ('cinemaReviewFile', models.FileField(upload_to='')),
                ('authorFirstName', models.CharField(max_length=15)),
                ('authorLastName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Golpo',
            fields=[
                ('golpoId', models.IntegerField(primary_key=True, serialize=False)),
                ('contentId', models.IntegerField()),
                ('golpoText', models.TextField()),
                ('authorFirstName', models.CharField(max_length=15)),
                ('authorLastName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RannaBanna',
            fields=[
                ('rannaBannaId', models.IntegerField(primary_key=True, serialize=False)),
                ('rannaBannaText', models.TextField()),
                ('rannaBannaFile', models.FileField(upload_to='')),
                ('authorFirstName', models.CharField(max_length=15)),
                ('authorLastName', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='kobita',
            name='authorFirstName',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='kobita',
            name='authorLastName',
            field=models.CharField(max_length=15),
        ),
    ]
