# Generated by Django 3.2.7 on 2021-10-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abirvab', '0003_auto_20211020_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('contentId', models.IntegerField(primary_key=True, serialize=False)),
                ('contentType', models.CharField(max_length=12)),
                ('contentAddingTime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='boibahar',
            name='contentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AddField(
            model_name='boireview',
            name='contentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AddField(
            model_name='chobi',
            name='contentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AddField(
            model_name='cinemareview',
            name='contentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AddField(
            model_name='other',
            name='contentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AddField(
            model_name='probondho',
            name='contentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AddField(
            model_name='rannabanna',
            name='contentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AlterField(
            model_name='golpo',
            name='contentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AlterField(
            model_name='kobita',
            name='contentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
    ]
