# Generated by Django 3.2.7 on 2021-10-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abirvab', '0004_auto_20211021_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contentType',
            field=models.CharField(choices=[('kobita', 'kobita'), ('golpo', 'golpo'), ('chobi', 'chobi'), ('cinemareview', 'cinemareview'), ('boireview', 'boireview'), ('rannabanna', 'rannabanna'), ('probondho', 'probondho'), ('boibahar', 'boibahar'), ('other', 'other')], max_length=12),
        ),
    ]
