# Generated by Django 3.2.7 on 2021-10-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abirvab', '0005_alter_content_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contentType',
            field=models.CharField(choices=[('kobita', 'kobita'), ('golpo', 'golpo'), ('chobi', 'chobi'), ('cinemaReview', 'cinemaReview'), ('boiReview', 'boiReview'), ('rannaBanna', 'rannaBanna'), ('probondho', 'probondho'), ('boiBahar', 'boiBahar'), ('other', 'other')], max_length=12),
        ),
    ]
