# Generated by Django 3.2.7 on 2021-10-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abirvab', '0006_alter_content_contenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='contentApproval',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('pending', 'pending')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='boibahar',
            name='contentId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AlterField(
            model_name='boireview',
            name='contentId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AlterField(
            model_name='chobi',
            name='contentId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AlterField(
            model_name='cinemareview',
            name='contentId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AlterField(
            model_name='golpo',
            name='contentId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AlterField(
            model_name='kobita',
            name='contentId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AlterField(
            model_name='other',
            name='contentId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AlterField(
            model_name='probondho',
            name='contentId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
        migrations.AlterField(
            model_name='rannabanna',
            name='contentId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='abirvab.content'),
        ),
    ]
